spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://113.44.190.45:3306/tk?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: tk
    password: 1234
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    check-template: true
    check-template-location: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 9201